# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - CodeFolio

on:
  push:
    branches:
      - codefolio-azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Show current working directory
        run: pwd

      - name: List all files and folders recursively
        run: ls -Rla ${{ github.workspace }}/..

      - name: Print github.workspace
        run: echo "github.workspace = ${{ github.workspace }}"  

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build with dotnet
        run: dotnet build CodeFolio.sln --configuration Release
        working-directory: ${{ github.workspace }}/CodeFolio-fresh

      - name: dotnet publish
        run: dotnet publish CodeFolio.sln -c Release -o ${{ github.workspace }}/publish
        working-directory: ${{ github.workspace }}/CodeFolio-fresh     

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_20757152030848D1BA58F0D2F1D2CEED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89F311D858A545AEA1AA65D61BF17825 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3142fd77-f976-4608-8124-a39018a8198f }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'codefolio-james'
          package: .
          slot-name: 'production'
